baseURL = 'https://triips-thecoder.github.io/hugo-hetic/'
languageCode = 'fr-fr'
title = 'Blog Hugo'
theme = 'gohugo-theme-ananke'

[params]
    description = "Un blog sur le d√©veloppement web, la programmation et les nouvelles technologies."
    custom_css = ['custom.css']
    showReadingTime = true
    featured_image = '/images/cookie-on-bowl.jpg'
