baseURL = 'https://github.com/Triips-TheCoder/hugo-hetic'
languageCode = 'fr-fr'
title = 'Mon nouveau blog Hugo'
theme = 'gohugo-theme-ananke'

# Paramètres spécifiques au thème Ananke
[params]
    description = "Un blog sur le développement web, la programmation et les nouvelles technologies."
    custom_css = ['custom.css']
    showReadingTime = true
    featured_image = '/images/banner.jpg'
